# platform :ios, '8.0'

target '金陵联赛' do
use_frameworks!

pod "AFNetworking"
pod "SDWebImage"
pod "YYModel"
pod "FMDB"
pod "SVProgressHUD"
pod "pop"
pod "LTMorphingLabel"
pod "Charts"
pod 'PageMenu'
pod 'AMapNavi', '~>2.3'
pod 'AMapSearch', '~>4.4'
pod 'AMapLocation', '~>2.3'
pod 'PPNumberButtonSwift',:git => 'https://github.com/jkpang/PPNumberButtonSwift.git'

  target '金陵联赛Tests' do
    inherit! :search_paths

  end

  target '金陵联赛UITests' do
    inherit! :search_paths

  end

end
